Register tags documentation example updated
harttle/liquidjs pull request #332
Opened 2021-04-13 06:56 UTC by kayuapi

2021-04-16 01:48 UTC, harttle requested changes

2021-04-16 01:48 UTC, harttle commented on docs/source/tutorials/register-filters-tags.md
>  ```javascript
update this to typescript

2021-04-16 01:48 UTC, harttle commented on docs/source/tutorials/register-filters-tags.md
> +    render: async function(ctx: Context, emitter: Emitter) {
good catch!

2021-04-16 02:55 UTC, kayuapi commented on docs/source/tutorials/register-filters-tags.md
>  ```javascript
done

2021-04-16 02:58 UTC, kayuapi commented on docs/source/tutorials/register-filters-tags.md
> +    render: async function(ctx: Context, emitter: Emitter) {
thanks!

2021-04-17 02:18 UTC, merged

2021-04-17 02:42 UTC, harttle commented
:tada: This PR is included in version 9.23.4 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/liquidjs/v/9.23.4)
- [GitHub release](https://github.com/harttle/liquidjs/releases/tag/v9.23.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: