Demo updated
harttle/liquidjs pull request #333
Opened 2021-04-13 07:48 UTC by kayuapi

2021-04-16 01:46 UTC, harttle requested changes

2021-04-16 01:46 UTC, harttle commented on demo/typescript/todolist.liquid
> +{%assign title = title%}
what is this line for?

2021-04-16 02:32 UTC, kayuapi commented on demo/typescript/todolist.liquid
> +{%assign title = title%}
oops, my bad! that line is unnecessary

2021-04-17 02:19 UTC, merged

2021-04-17 02:20 UTC, harttle commented
@all-contributors please add @kayuapi  for doc

2021-04-17 02:41 UTC, harttle commented
:tada: This PR is included in version 9.23.4 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/liquidjs/v/9.23.4)
- [GitHub release](https://github.com/harttle/liquidjs/releases/tag/v9.23.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: