fix: throw error on 'else if' tag
harttle/liquidjs pull request #669
Opened 2024-02-14 02:15 UTC by joel-hamilton

Throw an error if there is an invalid `else` tag:  #667

2024-02-14 02:17 UTC, harttle requested changes

2024-02-14 02:17 UTC, harttle commented on src/tokens/tag-token.ts
> +    this.tokenizer.assert(this.name !== 'else' || this.contentRange[1] - this.contentRange[0] === 4, () => `unexpected token: ${this.tokenizer.snapshot()}`)
Let's try move this into tags/if.ts

2024-02-14 02:18 UTC, harttle commented on src/tokens/tag-token.ts
> +    this.tokenizer.assert(this.name !== 'else' || this.contentRange[1] - this.contentRange[0] === 4, () => `unexpected token: ${this.tokenizer.snapshot()}`)
And maybe tags/unless as well

2024-02-16 00:25 UTC, joel-hamilton commented
Closing

2024-02-16 00:25 UTC, closed without merging