fix: allow liquidMethodMissing to return any supported value type
harttle/liquidjs pull request #698
Opened 2024-05-18 15:12 UTC by admtnnr

The issue is that the type of `liquidMethodMissing` is too restrictive and only allows returning `string` rather than any supported value type. I ran into this issue when trying to return a `Drop` from `liquidMethodMissing` to enable dynamic lookups along an entire accessor chain.

2024-05-19 06:32 UTC, harttle requested changes

2024-05-19 06:32 UTC, harttle commented on src/drop/drop.ts
> +  public liquidMethodMissing (key: string | number): Promise<any | undefined> | any | undefined {
```suggestion
  public liquidMethodMissing (key: string | number): Promise<any> | any {
```

2024-05-22 00:42 UTC, admtnnr commented
@harttle I think I addressed your single piece of feedback, let me know if there's anything else you'd like changed!

2024-05-22 04:35 UTC, merged

2024-05-22 04:36 UTC, harttle commented
@all-contributors please add @admtnnr for code